# Generated by Django 3.2.18 on 2023-03-01 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
        ('comments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_auto_20230218_1536'),
        ('games', '0003_game_description'),
        ('likes', '0002_auto_20230219_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='game',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='games.game'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('owner', 'post'), ('owner', 'comment'), ('owner', 'game'), ('owner', 'review')},
        ),
    ]
